apiVersion: v1
kind: Secret
metadata:
  name: contoso-air-secrets
  labels:
    app: contoso-air
type: Opaque
data:
  # Base64 encoded values for Cosmos DB access
  AZURE_COSMOS_CLIENTID: MmQ3N2JlNjUtOTYyZC00MDU0LWJiY2ItZWM3MzJlODdmYjNh
  AZURE_COSMOS_LISTCONNECTIONSTRINGURL: aHR0cHM6Ly9tYW5hZ2VtZW50LmF6dXJlLmNvbS9zdWJzY3JpcHRpb25zLzA1NWNiMGE1LWI0N2YtNDEyNS04NWI1LTk0NTU0YWQyNTRjMy9yZXNvdXJjZUdyb3Vwcy9yZy1jb250b3NvLWFpci1ha3MvcHJvdmlkZXJzL01pY3Jvc29mdC5Eb2N1bWVudERCL2RhdGFiYXNlQWNjb3VudHMvZGItY29udG9zb2FpcjE3NDkyNzczNDgvbGlzdENvbm5lY3Rpb25TdHJpbmdzP2FwaS12ZXJzaW9uPTIwMjEtMDQtMTU=
  AZURE_COSMOS_SCOPE: aHR0cHM6Ly9tYW5hZ2VtZW50LmF6dXJlLmNvbS8uZGVmYXVsdA==
